//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 09:03:50 AM ICT 
//


package com.project.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Words }
     * 
     */
    public Words createWords() {
        return new Words();
    }

    /**
     * Create an instance of {@link Pronounciation }
     * 
     */
    public Pronounciation createPronounciation() {
        return new Pronounciation();
    }

    /**
     * Create an instance of {@link Words.Word }
     * 
     */
    public Words.Word createWordsWord() {
        return new Words.Word();
    }

    /**
     * Create an instance of {@link WordDetail }
     * 
     */
    public WordDetail createWordDetail() {
        return new WordDetail();
    }

    /**
     * Create an instance of {@link Variants }
     * 
     */
    public Variants createVariants() {
        return new Variants();
    }

    /**
     * Create an instance of {@link WordInfos }
     * 
     */
    public WordInfos createWordInfos() {
        return new WordInfos();
    }

    /**
     * Create an instance of {@link Pronounciation.Reading }
     * 
     */
    public Pronounciation.Reading createPronounciationReading() {
        return new Pronounciation.Reading();
    }

    /**
     * Create an instance of {@link Words.Word.WordDetails }
     * 
     */
    public Words.Word.WordDetails createWordsWordWordDetails() {
        return new Words.Word.WordDetails();
    }

}
