//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 09:03:50 AM ICT 
//


package com.project.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wordDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wordDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pronounciation" type="{http://project.com/jaxb}pronounciation"/>
 *         &lt;element name="wordType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wordInfos" type="{http://project.com/jaxb}wordInfos"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wordDetail", propOrder = {
    "pronounciation",
    "wordType",
    "wordInfos"
})
public class WordDetail {

    @XmlElement(required = true)
    protected Pronounciation pronounciation;
    @XmlElement(required = true)
    protected String wordType;
    @XmlElement(required = true)
    protected WordInfos wordInfos;

    /**
     * Gets the value of the pronounciation property.
     * 
     * @return
     *     possible object is
     *     {@link Pronounciation }
     *     
     */
    public Pronounciation getPronounciation() {
        return pronounciation;
    }

    /**
     * Sets the value of the pronounciation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pronounciation }
     *     
     */
    public void setPronounciation(Pronounciation value) {
        this.pronounciation = value;
    }

    /**
     * Gets the value of the wordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWordType() {
        return wordType;
    }

    /**
     * Sets the value of the wordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWordType(String value) {
        this.wordType = value;
    }

    /**
     * Gets the value of the wordInfos property.
     * 
     * @return
     *     possible object is
     *     {@link WordInfos }
     *     
     */
    public WordInfos getWordInfos() {
        return wordInfos;
    }

    /**
     * Sets the value of the wordInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link WordInfos }
     *     
     */
    public void setWordInfos(WordInfos value) {
        this.wordInfos = value;
    }

}
