//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 09:03:50 AM ICT 
//


package com.project.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="word" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="unicodeString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wordString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="noOfStroke" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="variants" type="{http://project.com/jaxb}variants"/>
 *                   &lt;element name="wordDetails">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="wordDetail" type="{http://project.com/jaxb}wordDetail" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "word"
})
@XmlRootElement(name = "words")
public class Words {

    @XmlElement(required = true)
    protected List<Words.Word> word;

    /**
     * Gets the value of the word property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the word property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Words.Word }
     * 
     * 
     */
    public List<Words.Word> getWord() {
        if (word == null) {
            word = new ArrayList<Words.Word>();
        }
        return this.word;
    }

    public void setWord(List<Word> word) {
        this.word = word;
    }
    
    


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="unicodeString" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wordString" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="noOfStroke" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="variants" type="{http://project.com/jaxb}variants"/>
     *         &lt;element name="wordDetails">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="wordDetail" type="{http://project.com/jaxb}wordDetail" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Word {

        @XmlElement(required = true)
        protected String unicodeString;
        @XmlElement(required = true)
        protected String wordString;
        protected int noOfStroke;
        @XmlElement(required = true)
        protected Variants variants;
        @XmlElement(required = true)
        protected Words.Word.WordDetails wordDetails;

        /**
         * Gets the value of the unicodeString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnicodeString() {
            return unicodeString;
        }

        /**
         * Sets the value of the unicodeString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnicodeString(String value) {
            this.unicodeString = value;
        }

        /**
         * Gets the value of the wordString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWordString() {
            return wordString;
        }

        /**
         * Sets the value of the wordString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWordString(String value) {
            this.wordString = value;
        }

        /**
         * Gets the value of the noOfStroke property.
         * 
         */
        public int getNoOfStroke() {
            return noOfStroke;
        }

        /**
         * Sets the value of the noOfStroke property.
         * 
         */
        public void setNoOfStroke(int value) {
            this.noOfStroke = value;
        }

        /**
         * Gets the value of the variants property.
         * 
         * @return
         *     possible object is
         *     {@link Variants }
         *     
         */
        public Variants getVariants() {
            return variants;
        }

        /**
         * Sets the value of the variants property.
         * 
         * @param value
         *     allowed object is
         *     {@link Variants }
         *     
         */
        public void setVariants(Variants value) {
            this.variants = value;
        }

        /**
         * Gets the value of the wordDetails property.
         * 
         * @return
         *     possible object is
         *     {@link Words.Word.WordDetails }
         *     
         */
        public Words.Word.WordDetails getWordDetails() {
            return wordDetails;
        }

        /**
         * Sets the value of the wordDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link Words.Word.WordDetails }
         *     
         */
        public void setWordDetails(Words.Word.WordDetails value) {
            this.wordDetails = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="wordDetail" type="{http://project.com/jaxb}wordDetail" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "wordDetail"
        })
        public static class WordDetails {

            @XmlElement(required = true)
            protected List<WordDetail> wordDetail;

            /**
             * Gets the value of the wordDetail property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the wordDetail property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getWordDetail().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link WordDetail }
             * 
             * 
             */
            public List<WordDetail> getWordDetail() {
                if (wordDetail == null) {
                    wordDetail = new ArrayList<WordDetail>();
                }
                return this.wordDetail;
            }

            public void setWordDetail(List<WordDetail> wordDetail) {
                this.wordDetail = wordDetail;
            }
            
            

        }

    }

}
